### PR TITLE
fix 'dotnet build' command error for net35

### PR DESCRIPTION
**Pull request by hanabi1224**
error MSB3644: The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

### CODE REVIEW

**Comment by JeffreySu** [comment]
@hanabi1224  没有找到太多关于Net35FrameworkPathOverride的资料，有详细的说明文档吗？

**Comment by hanabi1224** [comment]
@JeffreySu 是自己写的 在 Directory.Build.props

**Comment by JeffreySu** [comment]
@hanabi1224 目的是什么呢？

**Comment by hanabi1224** [comment]
@JeffreySu   'dotnet build' 命令默认是打不到net35的安装库的，这个属性就是帮助强制定位一下net35的位置，dotnet build就能编译了

**Comment by JeffreySu** [comment]
@hanabi1224  能否重新PR到Developer分支，master分支不允许直接PR进来（会直接自动发布），谢谢！

**Comment by hanabi1224** [comment]
@JeffreySu 新发了一个PR: https://github.com/JeffreySu/WeiXinMPSDK/pull/1696

**Pull request closed without merging**
